locations = [{'active': True,
                'alternative_names': [],
                'code': 'BA',
                'continent': {'code': 'SA',
                              'id': 'south-america',
                              'name': 'South America',
                              'slug': 'south-america'},
                'country': {'code': 'AR',
                            'id': 'AR',
                            'name': 'Argentina',
                            'slug': 'argentina'},
                'global_rank_dst': 31,
                'id': 'BA_AR',
                'location': {'lat': -34.645238, 'lon': -58.393097},
                'name': 'Buenos Aires',
                'rank': 18,
                'region': {'id': 'southern-america',
                           'name': 'Southern America',
                           'slug': 'southern-america'},
                'slug': 'buenos-aires-state-argentina',
                'slug_en': 'buenos-aires-state-argentina',
                'type': 'subdivision'},
               {'active': True,
                'airports': 2,
                'alternative_departure_points': [{'distance': 31.73,
                                                  'duration': 1593.2,
                                                  'id': 'EZE'},
                                                 {'distance': 6.89,
                                                  'duration': 728.6,
                                                  'id': 'AEP'}],
                'alternative_names': [],
                'autonomous_territory': None,
                'bus_stations': 2,
                'car_rentals': [{'provider_id': 1175,
                                 'providers_locations': ['4297766',
                                                         '376931',
                                                         '4237289',
                                                         '4237292',
                                                         '672893']}],
                'code': 'BUE',
                'continent': {'code': 'SA',
                              'id': 'south-america',
                              'name': 'South America',
                              'slug': 'south-america'},
                'country': {'code': 'AR',
                            'id': 'AR',
                            'name': 'Argentina',
                            'slug': 'argentina'},
                'dst_popularity_score': 1318590.0,
                'global_rank_dst': 47,
                'hotels': 0,
                'id': 'buenos-aires_ba_ar',
                'location': {'lat': -34.603684, 'lon': -58.381559},
                'name': 'Buenos Aires',
                'nearby_country': None,
                'population': 13076300,
                'providers': [1175, 1266, 1277, 1282, 1283],
                'rank': 21,
                'region': {'id': 'southern-america',
                           'name': 'Southern America',
                           'slug': 'southern-america'},
                'slug': 'buenos-aires-buenos-aires-argentina',
                'slug_en': 'buenos-aires-buenos-aires-argentina',
                'stations': 0,
                'subdivision': {'code': 'BA',
                                'id': 'BA_AR',
                                'name': 'Buenos Aires',
                                'slug': 'buenos-aires-state-argentina'},
                'tags': [{'month_from': -1, 'month_to': -1, 'tag': 'beach'},
                         {'month_from': -1, 'month_to': -1, 'tag': 'nightlife'},
                         {'month_from': -1,
                          'month_to': -1,
                          'tag': 'sightseeing'}],
                'timezone': 'America/Argentina/Buenos_Aires',
                'type': 'city'},
               {'active': True,
                'alternative_names': [],
                'category': 'architecture',
                'code': 'la-boca-buenos-aires_poi',
                'global_rank_dst': 248,
                'id': 'la-boca-buenos-aires_poi',
                'location': {'lat': -34.63351, 'lon': -58.359042},
                'locations_nearby': [{'distance': 33.26,
                                      'duration': 1897,
                                      'id': 'EZE'},
                                     {'distance': 11.39,
                                      'duration': 1674,
                                      'id': 'AEP'},
                                     {'distance': 31.7,
                                      'duration': 1912,
                                      'id': 'EPA'}],
                'name': 'La Boca, Buenos Aires',
                'rank': 89,
                'slug': 'la-boca',
                'slug_en': 'la-boca',
                'type': 'special'},
               {'active': True,
                'airport_int_id': None,
                'alternative_departure_points': [{'distance': 247.7,
                                                  'duration': 14689,
                                                  'id': 'MVD'},
                                                 {'distance': 32.76,
                                                  'duration': 1752,
                                                  'id': 'EZE'},
                                                 {'distance': 8.2,
                                                  'duration': 742,
                                                  'id': 'AEP'}],
                'alternative_names': [],
                'car_rentals': [],
                'city': {'autonomous_territory': None,
                         'code': 'BUE',
                         'continent': {'code': 'SA',
                                       'id': 'south-america',
                                       'name': 'South America',
                                       'slug': 'south-america'},
                         'country': {'code': 'AR',
                                     'id': 'AR',
                                     'name': 'Argentina',
                                     'slug': 'argentina'},
                         'id': 'buenos-aires_ba_ar',
                         'name': 'Buenos Aires',
                         'nearby_country': None,
                         'region': {'id': 'southern-america',
                                    'name': 'Southern America',
                                    'slug': 'southern-america'},
                         'slug': 'buenos-aires-buenos-aires-argentina',
                         'subdivision': {'code': 'BA',
                                         'id': 'BA_AR',
                                         'name': 'Buenos Aires',
                                         'slug': 'buenos-aires-state-argentina'}},
                'code': 'AR-BUEN-TERM',
                'dst_popularity_score': 18.0,
                'global_rank_dst': 2048,
                'icao': None,
                'id': 'AR-BUEN-TERM',
                'int_id': 2578,
                'location': {'lat': -34.602137, 'lon': -58.368055},
                'name': 'Buenos Aires - Combis Puerto Madero',
                'new_ground': True,
                'providers': [1277, 1282, 1283],
                'rank': 2048,
                'routing_priority': 0,
                'slug': 'terminal-de-combis-puerto-madero-buenos-aires-buenos-aires-argentina',
                'slug_en': 'terminal-de-combis-puerto-madero-buenos-aires-buenos-aires-argentina',
                'special': [],
                'tags': [],
                'timezone': 'America/Argentina/Buenos_Aires',
                'tourist_region': [],
                'type': 'bus_station'},
               {'active': True,
                'airport_int_id': None,
                'alternative_departure_points': [{'distance': 249.7,
                                                  'duration': 14932,
                                                  'id': 'MVD'},
                                                 {'distance': 34.73,
                                                  'duration': 2061,
                                                  'id': 'EZE'},
                                                 {'distance': 6.39,
                                                  'duration': 686,
                                                  'id': 'AEP'}],
                'alternative_names': [],
                'car_rentals': [],
                'city': {'autonomous_territory': None,
                         'code': 'BUE',
                         'continent': {'code': 'SA',
                                       'id': 'south-america',
                                       'name': 'South America',
                                       'slug': 'south-america'},
                         'country': {'code': 'AR',
                                     'id': 'AR',
                                     'name': 'Argentina',
                                     'slug': 'argentina'},
                         'id': 'buenos-aires_ba_ar',
                         'name': 'Buenos Aires',
                         'nearby_country': None,
                         'region': {'id': 'southern-america',
                                    'name': 'Southern America',
                                    'slug': 'southern-america'},
                         'slug': 'buenos-aires-buenos-aires-argentina',
                         'subdivision': {'code': 'BA',
                                         'id': 'BA_AR',
                                         'name': 'Buenos Aires',
                                         'slug': 'buenos-aires-state-argentina'}},
                'code': 'AR-BUEN-RET0',
                'dst_popularity_score': 6.0,
                'global_rank_dst': 2048,
                'icao': None,
                'id': 'AR-BUEN-RET0',
                'int_id': 13414,
                'location': {'lat': -34.586564, 'lon': -58.374035},
                'name': 'Buenos Aires - Retiro',
                'new_ground': True,
                'providers': [1266, 1282],
                'rank': 2048,
                'routing_priority': 0,
                'slug': 'buenos-aires-retiro-buenos-aires-buenos-aires-argentina',
                'slug_en': 'buenos-aires-retiro-buenos-aires-buenos-aires-argentina',
                'special': [],
                'tags': [],
                'timezone': 'America/Argentina/Buenos_Aires',
                'tourist_region': [],
                'type': 'bus_station'}]
