from pprint import pprint
locations = [{'active': True,
                'alternative_names': [],
                'code': 'BA',
                'continent': {'code': 'SA',
                              'id': 'south-america',
                              'name': 'South America',
                              'slug': 'south-america'},
                'country': {'code': 'AR',
                            'id': 'AR',
                            'name': 'Argentina',
                            'slug': 'argentina'},
                'global_rank_dst': 31,
                'id': 'BA_AR',
                'location': {'lat': -34.645238, 'lon': -58.393097},
                'name': 'Buenos Aires',
                'rank': 18,
                'region': {'id': 'southern-america',
                           'name': 'Southern America',
                           'slug': 'southern-america'},
                'slug': 'buenos-aires-state-argentina',
                'slug_en': 'buenos-aires-state-argentina',
                'type': 'subdivision'},
               {'active': True,
                'airports': 2,
                'alternative_departure_points': [{'distance': 31.73,
                                                  'duration': 1593.2,
                                                  'id': 'EZE'},
                                                 {'distance': 6.89,
                                                  'duration': 728.6,
                                                  'id': 'AEP'}],
                'alternative_names': [],
                'autonomous_territory': None,
                'bus_stations': 2,
                'car_rentals': [{'provider_id': 1175,
                                 'providers_locations': ['4297766',
                                                         '376931',
                                                         '4237289',
                                                         '4237292',
                                                         '672893']}],
                'code': 'BUE',
                'continent': {'code': 'SA',
                              'id': 'south-america',
                              'name': 'South America',
                              'slug': 'south-america'},
                'country': {'code': 'AR',
                            'id': 'AR',
                            'name': 'Argentina',
                            'slug': 'argentina'},
                'dst_popularity_score': 1318590.0,
                'global_rank_dst': 47,
                'hotels': 0,
                'id': 'buenos-aires_ba_ar',
                'location': {'lat': -34.603684, 'lon': -58.381559},
                'name': 'Buenos Aires',
                'nearby_country': None,
                'population': 13076300,
                'providers': [1175, 1266, 1277, 1282, 1283],
                'rank': 21,
                'region': {'id': 'southern-america',
                           'name': 'Southern America',
                           'slug': 'southern-america'},
                'slug': 'buenos-aires-buenos-aires-argentina',
                'slug_en': 'buenos-aires-buenos-aires-argentina',
                'stations': 0,
                'subdivision': {'code': 'BA',
                                'id': 'BA_AR',
                                'name': 'Buenos Aires',
                                'slug': 'buenos-aires-state-argentina'},
                'tags': [{'month_from': -1, 'month_to': -1, 'tag': 'beach'},
                         {'month_from': -1, 'month_to': -1, 'tag': 'nightlife'},
                         {'month_from': -1,
                          'month_to': -1,
                          'tag': 'sightseeing'}],
                'timezone': 'America/Argentina/Buenos_Aires',
                'type': 'city'},
               {'active': True,
                'alternative_names': [],
                'category': 'architecture',
                'code': 'la-boca-buenos-aires_poi',
                'global_rank_dst': 248,
                'id': 'la-boca-buenos-aires_poi',
                'location': {'lat': -34.63351, 'lon': -58.359042},
                'locations_nearby': [{'distance': 33.26,
                                      'duration': 1897,
                                      'id': 'EZE'},
                                     {'distance': 11.39,
                                      'duration': 1674,
                                      'id': 'AEP'},
                                     {'distance': 31.7,
                                      'duration': 1912,
                                      'id': 'EPA'}],
                'name': 'La Boca, Buenos Aires',
                'rank': 89,
                'slug': 'la-boca',
                'slug_en': 'la-boca',
                'type': 'special'},
               {'active': True,
                'airport_int_id': None,
                'alternative_departure_points': [{'distance': 247.7,
                                                  'duration': 14689,
                                                  'id': 'MVD'},
                                                 {'distance': 32.76,
                                                  'duration': 1752,
                                                  'id': 'EZE'},
                                                 {'distance': 8.2,
                                                  'duration': 742,
                                                  'id': 'AEP'}],
                'alternative_names': [],
                'car_rentals': [],
                'city': {'autonomous_territory': None,
                         'code': 'BUE',
                         'continent': {'code': 'SA',
                                       'id': 'south-america',
                                       'name': 'South America',
                                       'slug': 'south-america'},
                         'country': {'code': 'AR',
                                     'id': 'AR',
                                     'name': 'Argentina',
                                     'slug': 'argentina'},
                         'id': 'buenos-aires_ba_ar',
                         'name': 'Buenos Aires',
                         'nearby_country': None,
                         'region': {'id': 'southern-america',
                                    'name': 'Southern America',
                                    'slug': 'southern-america'},
                         'slug': 'buenos-aires-buenos-aires-argentina',
                         'subdivision': {'code': 'BA',
                                         'id': 'BA_AR',
                                         'name': 'Buenos Aires',
                                         'slug': 'buenos-aires-state-argentina'}},
                'code': 'AR-BUEN-TERM',
                'dst_popularity_score': 18.0,
                'global_rank_dst': 2048,
                'icao': None,
                'id': 'AR-BUEN-TERM',
                'int_id': 2578,
                'location': {'lat': -34.602137, 'lon': -58.368055},
                'name': 'Buenos Aires - Combis Puerto Madero',
                'new_ground': True,
                'providers': [1277, 1282, 1283],
                'rank': 2048,
                'routing_priority': 0,
                'slug': 'terminal-de-combis-puerto-madero-buenos-aires-buenos-aires-argentina',
                'slug_en': 'terminal-de-combis-puerto-madero-buenos-aires-buenos-aires-argentina',
                'special': [],
                'tags': [],
                'timezone': 'America/Argentina/Buenos_Aires',
                'tourist_region': [],
                'type': 'bus_station'},
               {'active': True,
                'airport_int_id': None,
                'alternative_departure_points': [{'distance': 249.7,
                                                  'duration': 14932,
                                                  'id': 'MVD'},
                                                 {'distance': 34.73,
                                                  'duration': 2061,
                                                  'id': 'EZE'},
                                                 {'distance': 6.39,
                                                  'duration': 686,
                                                  'id': 'AEP'}],
                'alternative_names': [],
                'car_rentals': [],
                'city': {'autonomous_territory': None,
                         'code': 'BUE',
                         'continent': {'code': 'SA',
                                       'id': 'south-america',
                                       'name': 'South America',
                                       'slug': 'south-america'},
                         'country': {'code': 'AR',
                                     'id': 'AR',
                                     'name': 'Argentina',
                                     'slug': 'argentina'},
                         'id': 'buenos-aires_ba_ar',
                         'name': 'Buenos Aires',
                         'nearby_country': None,
                         'region': {'id': 'southern-america',
                                    'name': 'Southern America',
                                    'slug': 'southern-america'},
                         'slug': 'buenos-aires-buenos-aires-argentina',
                         'subdivision': {'code': 'BA',
                                         'id': 'BA_AR',
                                         'name': 'Buenos Aires',
                                         'slug': 'buenos-aires-state-argentina'}},
                'code': 'AR-BUEN-RET0',
                'dst_popularity_score': 6.0,
                'global_rank_dst': 2048,
                'icao': None,
                'id': 'AR-BUEN-RET0',
                'int_id': 13414,
                'location': {'lat': -34.586564, 'lon': -58.374035},
                'name': 'Buenos Aires - Retiro',
                'new_ground': True,
                'providers': [1266, 1282],
                'rank': 2048,
                'routing_priority': 0,
                'slug': 'buenos-aires-retiro-buenos-aires-buenos-aires-argentina',
                'slug_en': 'buenos-aires-retiro-buenos-aires-buenos-aires-argentina',
                'special': [],
                'tags': [],
                'timezone': 'America/Argentina/Buenos_Aires',
                'tourist_region': [],
                'type': 'bus_station'}]


flight_search_result = {'all_stopover_airports': [],
 'currency': 'USD',
 'data': [{'airlines': ['DL'],
           'availability': {'seats': 1},
           'baglimit': {'hand_height': 35,
                        'hand_length': 56,
                        'hand_weight': 10,
                        'hand_width': 23,
                        'hold_dimensions_sum': 157,
                        'hold_height': 52,
                        'hold_length': 78,
                        'hold_weight': 23,
                        'hold_width': 27,
                        'personal_item_height': 30,
                        'personal_item_length': 40,
                        'personal_item_weight': 3,
                        'personal_item_width': 10},
           'bags_price': {'1': 84.98, '2': 198.282},
           'booking_token': 'EFdO9ydDDqjqw_MLkqgrmSxV7jlDgyqriSIetv1W2E5ibDKQqnptUcdtF7gWhp1rCkUvo7eYGhiw0wg2ipKrvbAagIwLJtu1EUpun6xNbx6DHDS9KOjVsk9_3X-rlz-JsepaaRdTlP13s2DDGfVykC9XYG2pPHfqMJJjgvhS6-Pg9QUDfrFLD5dZOMobFBpbcXMJWgdmwOksb6O4McB2wOUKAhBzKVnN158N054alxm9wCwqNfUfuFFzOgswYdkmnMm81C6OdGyB4dw6fbwP8FenL8jAM7Di7JdMA5wZ0WVLwEm0SAA8-blaXFqXw6_sXkUxnuGZUtL0p3aHxVCrqsA35iNGKTg725NHJUHw9Qk83DDOc__m4tSuV5oSP__koH1QVCgN2M8VUoyhXELJ7rpfl6Mn9rVmEHchicKSvPzRGdFTfktYWFQ7d_eMMiKNVsLaIWS_NLLopchMCvXZzhGS8mndYegQg7uyamGhcTODxGp1Y_nY9oW1eA_vAYtQ_',
           'cityCodeFrom': 'MIA',
           'cityCodeTo': 'NYC',
           'cityFrom': 'Miami',
           'cityTo': 'New York',
           'conversion': {'EUR': 231.663932, 'USD': 229.0044},
           'countryFrom': {'code': 'US', 'name': 'United States'},
           'countryTo': {'code': 'US', 'name': 'United States'},
           'deep_link': 'https://www.kiwi.com/deep?affilid=zalogonzalogon&currency=USD&flightsId=0f6b22ee4b7e4b84ef758887_0%7C0f6b22ee4b7e4b84ef758887_1&from=MIA&lang=en&passengers=1&searchBags=1.1&to=LGA&booking_token=EFdO9ydDDqjqw_MLkqgrmSxV7jlDgyqriSIetv1W2E5ibDKQqnptUcdtF7gWhp1rCkUvo7eYGhiw0wg2ipKrvbAagIwLJtu1EUpun6xNbx6DHDS9KOjVsk9_3X-rlz-JsepaaRdTlP13s2DDGfVykC9XYG2pPHfqMJJjgvhS6-Pg9QUDfrFLD5dZOMobFBpbcXMJWgdmwOksb6O4McB2wOUKAhBzKVnN158N054alxm9wCwqNfUfuFFzOgswYdkmnMm81C6OdGyB4dw6fbwP8FenL8jAM7Di7JdMA5wZ0WVLwEm0SAA8-blaXFqXw6_sXkUxnuGZUtL0p3aHxVCrqsA35iNGKTg725NHJUHw9Qk83DDOc__m4tSuV5oSP__koH1QVCgN2M8VUoyhXELJ7rpfl6Mn9rVmEHchicKSvPzRGdFTfktYWFQ7d_eMMiKNVsLaIWS_NLLopchMCvXZzhGS8mndYegQg7uyamGhcTODxGp1Y_nY9oW1eA_vAYtQ_',
           'distance': 1770.31,
           'duration': {'departure': 10740, 'return': 11700, 'total': 22440},
           'facilitated_booking_available': True,
           'fare': {'adults': 229, 'children': 229, 'infants': 229},
           'flyFrom': 'MIA',
           'flyTo': 'LGA',
           'has_airport_change': False,
           'hidden_city_ticketing': False,
           'id': '0f6b22ee4b7e4b84ef758887_0|0f6b22ee4b7e4b84ef758887_1',
           'local_arrival': '2022-11-30T09:59:00.000Z',
           'local_departure': '2022-11-30T07:00:00.000Z',
           'nightsInDest': 6,
           'pnr_count': 1,
           'price': 229.0044,
           'quality': 305.530414,
           'route': [{'airline': 'DL',
                      'bags_recheck_required': False,
                      'cityCodeFrom': 'MIA',
                      'cityCodeTo': 'NYC',
                      'cityFrom': 'Miami',
                      'cityTo': 'New York',
                      'combination_id': '0f6b22ee4b7e4b84ef758887',
                      'equipment': None,
                      'fare_basis': 'VRUNC2BG',
                      'fare_category': 'M',
                      'fare_classes': 'E',
                      'fare_family': '',
                      'flight_no': 1653,
                      'flyFrom': 'MIA',
                      'flyTo': 'LGA',
                      'guarantee': False,
                      'id': '0f6b22ee4b7e4b84ef758887_0',
                      'local_arrival': '2022-11-30T09:59:00.000Z',
                      'local_departure': '2022-11-30T07:00:00.000Z',
                      'operating_carrier': 'DL',
                      'operating_flight_no': '1653',
                      'return': 0,
                      'utc_arrival': '2022-11-30T14:59:00.000Z',
                      'utc_departure': '2022-11-30T12:00:00.000Z',
                      'vehicle_type': 'aircraft',
                      'vi_connection': False},
                     {'airline': 'DL',
                      'bags_recheck_required': False,
                      'cityCodeFrom': 'NYC',
                      'cityCodeTo': 'MIA',
                      'cityFrom': 'New York',
                      'cityTo': 'Miami',
                      'combination_id': '0f6b22ee4b7e4b84ef758887',
                      'equipment': None,
                      'fare_basis': 'VRUNC2BG',
                      'fare_category': 'M',
                      'fare_classes': 'E',
                      'fare_family': '',
                      'flight_no': 1370,
                      'flyFrom': 'LGA',
                      'flyTo': 'MIA',
                      'guarantee': False,
                      'id': '0f6b22ee4b7e4b84ef758887_1',
                      'local_arrival': '2022-12-06T10:15:00.000Z',
                      'local_departure': '2022-12-06T07:00:00.000Z',
                      'operating_carrier': 'DL',
                      'operating_flight_no': '1370',
                      'return': 1,
                      'utc_arrival': '2022-12-06T15:15:00.000Z',
                      'utc_departure': '2022-12-06T12:00:00.000Z',
                      'vehicle_type': 'aircraft',
                      'vi_connection': False}],
           'technical_stops': 0,
           'throw_away_ticketing': False,
           'utc_arrival': '2022-11-30T14:59:00.000Z',
           'utc_departure': '2022-11-30T12:00:00.000Z',
           'virtual_interlining': False}],
 'fx_rate': 0.98852,
 'search_id': 'ee1346f1-7c16-0eec-d59d-ddc800bc477e',
 'search_params': {'flyFrom_type': 'airport',
                   'seats': {'adults': 1,
                             'children': 0,
                             'infants': 0,
                             'passengers': 1},
                   'to_type': 'airport'},
 'sort_version': 0}

print(flight_search_result["data"][0]["price"])